apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://10.0.0.1
  name: secure-apiserver
contexts:
- context:
    cluster: secure-apiserver
    namespace: default
    user: kube-user
  name: main
current-context: main
kind: Config
preferences: {}
users:
- name: kube-user
  user:
    token: /var/run/secrets/kubernetes.io/serviceaccount/token


# This is a file that may be used in pods to connect securely to the apiserver