apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: kube-system
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: kubernetesonarm/elasticsearch
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: kube-system-esdb
        - name: NODE_MASTER
          value: true
        - name: NODE_DATA
          value: false
        - name: HTTP_ENABLE
          value: false
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
          - emptyDir:
              medium: ""
            name: storage
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: kube-system
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: kubernetesonarm/elasticsearch
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: kube-system-esdb
        - name: NODE_MASTER
          value: false
        - name: HTTP_ENABLE
          value: false
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
          - emptyDir: {}
            name: storage
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: kube-system
  name: es-client
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: client
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-client
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: kubernetesonarm/elasticsearch
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: kube-system-esdb
        - name: NODE_MASTER
          value: false
        - name: NODE_DATA
          value: false
        - name: HTTP_ENABLE
          value: true
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
          - emptyDir: {}
            name: storage
