apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  namespace: kube-system
  labels:
    k8s-app: registry
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: registry
  template:
    metadata:
      labels:
        k8s-app: registry
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: kubernetesonarm/registry
        imagePullPolicy: IfNotPresent
        args:
        - /etc/docker/registry/config.yml
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: registry-data
        hostPath:
          path: /var/lib/registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
  labels:
    k8s-app: registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: registry
  clusterIP: 10.0.0.20
  ports:
  - name: registry
    port: 5000
    protocol: TCP
