FROM luxas/go

#RUN GOPATH=$GOPATH/src/github.com/docker/distribution/Godeps/_workspace:$GOPATH && go get github.com/docker/distribution/cmd/registry

RUN GOPATH=$GOPATH/src/github.com/docker/distribution/Godeps/_workspace:$GOPATH && \
	mkdir -p /gopath/src/github.com/docker && \
	cd /gopath/src/github.com/docker && \
	curl -sSL https://github.com/docker/distribution/archive/v2.1.1.tar.gz | tar -xz && \
	mv dist* distribution && \
	make PREFIX=/gopath clean binaries